config/routes.rb
Rails.application.routes.draw do
  resources :books
  resources :authors
  resources :accounts
  resources :suppliers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/supplier.rb
class Supplier < ApplicationRecord
    has_one :account
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: %i[ show edit update destroy ]

  # GET /suppliers or /suppliers.json
  def index
    @suppliers = Supplier.all
  end

  # GET /suppliers/1 or /suppliers/1.json
  def show
  end

  # GET /suppliers/new
  def new
    @supplier = Supplier.new
  end

  # GET /suppliers/1/edit
  def edit
  end

  # POST /suppliers or /suppliers.json
  def create
    @supplier = Supplier.new(supplier_params)

    respond_to do |format|
      if @supplier.save
        format.html { redirect_to supplier_url(@supplier), notice: "Supplier was successfully created." }
        format.json { render :show, status: :created, location: @supplier }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suppliers/1 or /suppliers/1.json
  def update
    respond_to do |format|
      if @supplier.update(supplier_params)
        format.html { redirect_to supplier_url(@supplier), notice: "Supplier was successfully updated." }
        format.json { render :show, status: :ok, location: @supplier }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suppliers/1 or /suppliers/1.json
  def destroy
    @supplier.destroy

    respond_to do |format|
      format.html { redirect_to suppliers_url, notice: "Supplier was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supplier
      @supplier = Supplier.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def supplier_params
      params.require(:supplier).permit(:name)
    end
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/suppliers/_form.html.erb
<%= form_with(model: supplier) do |form| %>
  <% if supplier.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(supplier.errors.count, "error") %> prohibited this supplier from being saved:</h2>

      <ul>
        <% supplier.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/suppliers/_supplier.html.erb
<div id="<%= dom_id supplier %>">
  <p>
    <strong>Name:</strong>
    <%= supplier.name %>
  </p>

</div>

app/views/suppliers/edit.html.erb
<h1>Editing supplier</h1>

<%= render "form", supplier: @supplier %>

<br>

<div>
  <%= link_to "Show this supplier", @supplier %> |
  <%= link_to "Back to suppliers", suppliers_path %>
</div>

app/views/suppliers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Suppliers</h1>

<div id="suppliers">
  <% @suppliers.each do |supplier| %>
    <%= render supplier %>
    <p>
      <%= link_to "Show this supplier", supplier %>
    </p>
  <% end %>
</div>

<%= link_to "New supplier", new_supplier_path %>

app/views/suppliers/new.html.erb
<h1>New supplier</h1>

<%= render "form", supplier: @supplier %>

<br>

<div>
  <%= link_to "Back to suppliers", suppliers_path %>
</div>

app/views/suppliers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @supplier %>

<div>
  <%= link_to "Edit this supplier", edit_supplier_path(@supplier) %> |
  <%= link_to "Back to suppliers", suppliers_path %>

  <%= button_to "Destroy this supplier", @supplier, method: :delete %>
</div>